### ISSUE TITLE
README等OSSの整備

### ISSUE THREAD

**Issue by Qs-F** [4-design/for-ui#848]
- README.mdをいい感じに (ロゴ, version tag, install方法, author, license)
- pull_request_templateを作り直す

**Comment by nora** [comment]
## 3design-ui => for-ui upgrade メモ (for Next.js)

いくらか躓いたのでメモを残しておきます

### 1. TailwindCSS の ClassNameによるStyleが効くようにする
 
- `global.css` 作成
  - `@tailwind base;` など
- `app.tsx` でimport

### 2. `tailwind.config.js` の設定

- preset読み込み
  - `preset: [require('@4design/for-ui/tailwind.config.base.js')]`
  - 3design-ui の preset は不要
- `important: '#root'` (or `true`)
  - MUI のスタイルを独自スタイルで上書きさせるため
  - セレクタは問わない

### 3. `post.css.config` の設定

post.css.config が存在しない場合は作成する
→ デフォルトの構成を自分で定義する必要があることに注意 ([参考](https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-plugins))

そして以下を追加

```js
plugins: {
  tailwindcss: {},
  autoprefixer: {},
  // ...
}
```
