### ISSUE TITLE
デザイン改善: Select

### ISSUE THREAD

**Issue by Qs-F** [4-design/for-ui#868]
- [x] Design
- [x] Dev

**Comment by kotobuki562** [comment]
@Qs-F 
これって既にフォントサイズ変更されてますかね？？

**Comment by Qs-F** [comment]
@kotobuki562 Figma側まだ変更掛けられてません！すみません！ただ内部的にはTextFieldのスタイルをそのまま使いまわしているのでTextFieldの更新が終わればこれも終わるはずという算段です!
