### ISSUE TITLE
vercel からの移行

### ISSUE THREAD

**Issue by locona** [4-design/for-ui#899]
https://pages.cloudflare.com/
https://www.netlify.com/

**Comment by Qs-F** [comment]
# FUI Storybook ホスティングのVercelからの移行先メモ

## Cloudflare Pages

### Pros

- 無料でいけそう
- 表示が速い
- deployも最近は速い
- branch preview可能

### Cons

- 1 Repo : 1サイトとなっている (monorepoで複数サイトをCloudflare Pagesでdeployはできない)

## Netlify

### Pros

- branch preview可能
- reviewのときにデザイナーが介入しやすい仕組みがある [参考](https://docs.netlify.com/site-deploys/deploy-previews/)
- deployは速い

### Cons

- build minutes等が足りなくなると自動的にプランが挙げられて請求が来る
  - 止めることはできない
- 日本にサーバーがないので表示が遅い

# 所感

- 機能的に使いやすいのはNetlifyだけど使いこなせるかは微妙 (現状だとデザイン上のチェックでレビューするのが自分なので不要、デザイナーをもっと巻き込んでいくならあると嬉しい)
- Netlifyのbuild minutesを超えると自動で $8 課金とかになるのでこれは辛い (私も一回やらかしました)
- 速度的にはどっちでもいい
- いい感じに収めるなら
  - Cloudflare PagesでStorybookをホスティング
  - その他はVercelでホスティング (exampleはbranch previewなくてもいいと思うので (あったら嬉しいが))

**Comment by Qs-F** [comment]
完了済みなのでclose
